src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::group(['prefix' => '/', 'as' => 'site.', 'middleware' => 'locale'], function() {
    Route::get('/', 'Site\IndexController@index')->name('index');
    Route::get('/locale/{locale}', 'Site\LanguageController@setLocale')->name('locale');
    Route::group(['prefix' => '/product', 'as' => 'product.'], function() {
        Route::get('/all', 'Site\ProductController@index')->name('index');
        Route::get('/{slug}', 'Site\ProductController@show')->name('show');
    });
    Route::group(['prefix' => '/review', 'as' => 'review.'], function() {
        Route::post('/store', 'Site\ReviewController@store')->name('store');
    });
});

Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => ['admin', 'locale']], function() {

    Route::get('/', 'Admin\AdminController@index')->name('index');

    Route::group(['prefix' => '/user', 'as' => 'user.'], function() {
        Route::get('/all', 'Admin\UserController@index')->name('index');
        Route::get('/create', 'Admin\UserController@create')->name('create');
        Route::post('/store', 'Admin\UserController@store')->name('store');
        Route::get('/{id}', 'Admin\UserController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\UserController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\UserController@update')->name('update');
        Route::get('/{id}/edit/password', 'Admin\UserController@editPassword')->name('edit.password');
        Route::post('/{id}/update/password', 'Admin\UserController@updatePassword')->name('update.password');
        Route::get('/{id}/destroy', 'Admin\UserController@destroy')->name('destroy');
    });

    Route::group(['prefix' => '/role', 'as' => 'role.'], function() {
        Route::get('/all', 'Admin\RoleController@index')->name('index');
        Route::get('/create', 'Admin\RoleController@create')->name('create');
        Route::post('/store', 'Admin\RoleController@store')->name('store');
        Route::get('/{id}', 'Admin\RoleController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\RoleController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\RoleController@update')->name('update');
        Route::get('/{id}/destroy', 'Admin\RoleController@destroy')->name('destroy');
    });

    Route::group(['prefix' => '/product', 'as' => 'product.'], function() {
        Route::get('/all', 'Admin\ProductController@index')->name('index');
        Route::get('/create', 'Admin\ProductController@create')->name('create');
        Route::post('/store', 'Admin\ProductController@store')->name('store');
        Route::get('/{id}', 'Admin\ProductController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\ProductController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\ProductController@update')->name('update');
        Route::get('/{id}/destroy', 'Admin\ProductController@destroy')->name('destroy');
    });

    Route::group(['prefix' => '/status', 'as' => 'status.'], function() {
        Route::get('/all', 'Admin\StatusController@index')->name('index');
        Route::get('/create', 'Admin\StatusController@create')->name('create');
        Route::post('/store', 'Admin\StatusController@store')->name('store');
        Route::get('/{id}', 'Admin\StatusController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\StatusController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\StatusController@update')->name('update');
        Route::get('/{id}/destroy', 'Admin\StatusController@destroy')->name('destroy');
    });
    Route::group(['prefix' => '/review', 'as' => 'review.'], function() {
        Route::get('/all', 'Admin\ReviewController@index')->name('index');
        Route::get('/create', 'Admin\ReviewController@create')->name('create');
        Route::post('/store', 'Admin\ReviewController@store')->name('store');
        Route::get('/{id}', 'Admin\ReviewController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\ReviewController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\ReviewController@update')->name('update');
        Route::get('/{id}/destroy', 'Admin\ReviewController@destroy')->name('destroy');
    });

});

src/app/Models/Product.php
<?php

namespace App\Models;

use App\Models\Review;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';

    protected $fillable = [
        'name',
        'slug',
        'description',
        'price',
    ];

    public function reviews()
    {
        return $this->hasMany(Review::class);
    }

    public function reviewsUnRejected()
    {
        return $this->reviews()
                    ->where('statuses_id_foreign', '<>', Status::whereSlug('rejected')->id);
    }
}

src/app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Product;
use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use Illuminate\Http\Request;
use Log;

class ProductController extends Controller
{
    public function index()
    {
        return view('admin/product/index', [
            'products' => Product::all(),
        ]);
    }

    public function show($id)
    {
        return view('admin/product/detail', [
            'product' => Product::find($id),
        ]);
    }

    public function create()
    {
        return view('admin/product/create');
    }


    public function store(ProductRequest $request)
    {
        $product = new Product;
        $product->fill($request->validated());
        $product->picture = storePictureOrNull($product->slug, $request->file('picture'));
        $product->save();

        Log::debug('Product [id: '.$product->id.'] successfully stored');

        return redirect()->route('admin.product.show', $product->id)
                         ->with('success', 'Product added');
    }

    public function edit($id) {
        return view('admin/product/update', [
            'product' => Product::find($id),
        ]);
    }

    public function update($id, ProductRequest $request) {
        $product = Product::find($id);
        $product->fill($request->validated());
        $product->picture = storePictureOrNull($product->slug, $request->file('picture')) ?? $product->picture;
        $product->update();

        Log::debug('Product [id: '.$product->id.'] successfully updated');

        return redirect()->route('admin.product.show', $product->id)
                         ->with('success', 'Product updated');
    }

    public function destroy($id) {
        Product::find($id)->delete();

        Log::debug('Product [id: '.$id.'] successfully destroyed');

        return redirect()->route('admin.product.index')
                         ->with('success', 'Product destroyed');
    }
}

src/app/Http/Controllers/Site/ProductController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\Review;
use App\Models\Status;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index()
    {
        return view('site/product/index', [
            'products' => Product::orderBy('id', 'desc')->paginate(6),
        ]);
    }

    public function show($slug)
    {
        return view('site/product/detail', [
            'product' => Product::where('slug', '=', $slug)->firstOrFail(),
        ]);
    }
}

src/resources/views/admin/product/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="card-header">
        <h1> Dashboard - [Products] </h1>
    </div>

    <div class="card-body">

        <form action="{{ route('admin.product.store') }}" method="post" enctype="multipart/form-data">

            @csrf

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Name <span class="text-danger">*</span> </span>
                </div>
                <input type="text" name="name" class="form-control">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Slug </span>
                </div>
                <input type="text" name="slug" class="form-control">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Picture </span>
                </div>
                <input type="file" name="picture" class="form-control">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Description </span>
                </div>
                <textarea class="form-control" name="description" cols="30" rows="10"></textarea>
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Price <span class="text-danger">*</span> </span>
                </div>
                <input type="number" step="any" name="price" class="form-control">
            </div>

            <div class="btn-group mt-1" role="group" aria-label="Basic example">
                <a class="btn btn-primary" href="{{ route('admin.product.index') }}"> Back </a>
                <button class="btn btn-success" type="submit"> Store </button>
            </div>

        </form>

    </div>

@endsection

src/resources/views/admin/product/detail.blade.php
@extends('layouts.app')

@section('content')

    <div class="card-header">
        <h1> Dashboard - [Products] {{ $product->name }} </h1>
    </div>

    <div class="card-body">

        <ul class="list-group">
            @if ($product->picture)
                <div class="text-center mb-3">
                    <img width="128"class="img-fluid" src="{{ asset('storage/pictures/'.$product->picture) }}">
                </div>
            @endif
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $product->id ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> id </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $product->name ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> name </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $product->slug ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> slug </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $product->picture ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> picture </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $product->description ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> description </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $product->price ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> price </span>
            </li>
        </ul>

        <div class="btn-group mt-1" role="group" aria-label="Basic example">
            <a class="btn btn-primary" href="{{ route('admin.product.index') }}"> Back </a>
            <a class="btn btn-success" href="{{ route('admin.product.edit', $product->id) }}"> Edit </a>
            <a class="btn btn-danger" href="{{ route('admin.product.destroy', $product->id) }}"> Destroy </a>
        </div>

    </div>

@endsection

src/resources/views/admin/product/index.blade.php
@extends('layouts.app')

@section('content')

    @include('admin.includes.links')

    <div class="card">

        <div class="card-header black">
            <h1 class="h1 white-text text-uppercase"> Products table </h1>
        </div>

        <div class="card-body">
            <table class="table table-striped table-bordered table-hover table-sm table-responsive text-nowrap text-center">
                <thead>
                    <tr>
                        <th scope="col"> ID </th>
                        <th scope="col"> name </th>
                        <th scope="col"> slug </th>
                        <th scope="col"> picture </th>
                        <th scope="col"> description </th>
                        <th scope="col"> price </th>
                        <th scope="col"> created at </th>
                        <th scope="col"> updated at </th>
                        <th scope="col"> tools </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($products as $product)
                        <tr>
                            <th scope="row"> {{ $product->id }} </th>
                            <td> {{ $product->name }} </td>
                            <td> {{ $product->slug }} </td>
                            <td> {{ $product->picture }} </td>
                            <td> {{ Str::words($product->description, 10) }} </td>
                            <td> {{ $product->price }} </td>
                            <td> {{ $product->created_at }} </td>
                            <td> {{ $product->updated_at }} </td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    <a type="button" class="btn btn-dark" href="{{ route('admin.product.show', $product->id) }}"> <i class="fas fa-info"></i> </a>
                                    <a type="button" class="btn btn-dark" href="{{ route('admin.product.edit', $product->id) }}"> <i class="fas fa-edit"></i> </a>
                                    <a type="button" class="btn btn-danger" href="{{ route('admin.product.destroy', $product->id) }}"> <i class="fas fa-trash"></i> </a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th scope="col"> ID </th>
                        <th scope="col"> name </th>
                        <th scope="col"> slug </th>
                        <th scope="col"> picture </th>
                        <th scope="col"> description </th>
                        <th scope="col"> price </th>
                        <th scope="col"> created at </th>
                        <th scope="col"> updated at </th>
                        <th scope="col"> tools </th>
                    </tr>
                </tfoot>
            </table>
        </div>

        <div class="card-footer black">
            <div class="btn-group" role="group" aria-label="Basic example">
                <a class="btn btn-white black-text" href="{{ route('admin.product.create') }}"> Store <i class="fas fa-plus"></i> </a>
            </div>

        </div>

    </div>

    @include('admin.includes.tables')

@endsection

src/resources/views/admin/product/update.blade.php
@extends('layouts.app')

@section('content')

    <div class="card-header">
        <h1> Dashboard - [Products] {{ $product->name }} </h1>
    </div>

    <div class="card-body">

        <form action="{{ route('admin.product.update', $product->id) }}" method="post" enctype="multipart/form-data">

            @csrf

            @if ($product->picture)
                <div class="text-center mb-3">
                    <img width="128"class="img-fluid" src="{{ asset('storage/pictures/'.$product->picture) }}">
                </div>
            @endif

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Name </span>
                </div>
                <input type="text" name="name" class="form-control" value="{{ $product->name }}">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Slug </span>
                </div>
                <input type="text" name="slug" class="form-control" value="{{ $product->slug }}">
            </div>

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroupFileAddon01"> Picture </span>
                </div>
                <div class="custom-file">
                    <input type="file" class="custom-file-input" name="picture" value="{{ $product->picture }}">
                    <label class="custom-file-label"> {{ $request->file ?? $product->picture ?? 'Choose file' }} </label>
                </div>
            </div>

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Description </span>
                </div>
                <textarea class="form-control" name="description" cols="30" rows="5"> {{ $product->description }} </textarea>
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Price </span>
                </div>
                <input type="number" step="any" name="price" class="form-control" value="{{ $product->price }}">
            </div>

            <div class="btn-group mt-1" role="group" aria-label="Basic example">
                <a class="btn btn-primary" href="{{ route('admin.product.show', $product->id) }}"> Back </a>
                <button class="btn btn-success" type="submit"> Update </button>
            </div>

        </form>

    </div>

@endsection