src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::group(['prefix' => '/', 'as' => 'site.', 'middleware' => 'locale'], function() {
    Route::get('/', 'Site\IndexController@index')->name('index');
    Route::get('/locale/{locale}', 'Site\LanguageController@setLocale')->name('locale');
    Route::group(['prefix' => '/product', 'as' => 'product.'], function() {
        Route::get('/all', 'Site\ProductController@index')->name('index');
        Route::get('/{slug}', 'Site\ProductController@show')->name('show');
    });
    Route::group(['prefix' => '/review', 'as' => 'review.'], function() {
        Route::post('/store', 'Site\ReviewController@store')->name('store');
    });
});

Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => ['admin', 'locale']], function() {

    Route::get('/', 'Admin\AdminController@index')->name('index');

    Route::group(['prefix' => '/user', 'as' => 'user.'], function() {
        Route::get('/all', 'Admin\UserController@index')->name('index');
        Route::get('/create', 'Admin\UserController@create')->name('create');
        Route::post('/store', 'Admin\UserController@store')->name('store');
        Route::get('/{id}', 'Admin\UserController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\UserController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\UserController@update')->name('update');
        Route::get('/{id}/edit/password', 'Admin\UserController@editPassword')->name('edit.password');
        Route::post('/{id}/update/password', 'Admin\UserController@updatePassword')->name('update.password');
        Route::get('/{id}/destroy', 'Admin\UserController@destroy')->name('destroy');
    });

    Route::group(['prefix' => '/role', 'as' => 'role.'], function() {
        Route::get('/all', 'Admin\RoleController@index')->name('index');
        Route::get('/create', 'Admin\RoleController@create')->name('create');
        Route::post('/store', 'Admin\RoleController@store')->name('store');
        Route::get('/{id}', 'Admin\RoleController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\RoleController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\RoleController@update')->name('update');
        Route::get('/{id}/destroy', 'Admin\RoleController@destroy')->name('destroy');
    });

    Route::group(['prefix' => '/product', 'as' => 'product.'], function() {
        Route::get('/all', 'Admin\ProductController@index')->name('index');
        Route::get('/create', 'Admin\ProductController@create')->name('create');
        Route::post('/store', 'Admin\ProductController@store')->name('store');
        Route::get('/{id}', 'Admin\ProductController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\ProductController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\ProductController@update')->name('update');
        Route::get('/{id}/destroy', 'Admin\ProductController@destroy')->name('destroy');
    });

    Route::group(['prefix' => '/status', 'as' => 'status.'], function() {
        Route::get('/all', 'Admin\StatusController@index')->name('index');
        Route::get('/create', 'Admin\StatusController@create')->name('create');
        Route::post('/store', 'Admin\StatusController@store')->name('store');
        Route::get('/{id}', 'Admin\StatusController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\StatusController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\StatusController@update')->name('update');
        Route::get('/{id}/destroy', 'Admin\StatusController@destroy')->name('destroy');
    });
    Route::group(['prefix' => '/review', 'as' => 'review.'], function() {
        Route::get('/all', 'Admin\ReviewController@index')->name('index');
        Route::get('/create', 'Admin\ReviewController@create')->name('create');
        Route::post('/store', 'Admin\ReviewController@store')->name('store');
        Route::get('/{id}', 'Admin\ReviewController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\ReviewController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\ReviewController@update')->name('update');
        Route::get('/{id}/destroy', 'Admin\ReviewController@destroy')->name('destroy');
    });

});

src/app/Models/Status.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Status extends Model
{
    protected $table = 'statuses';

    public $timestamps = false;

    protected $fillable = [
        'name',
        'slug',
        'color_bg',
        'color_fg',
    ];

    public function reviews()
    {
        return $this->hasMany(Product::class);
    }

    public static function whereSlug($value)
    {
        return Status::where('slug', '=', $value)->firstOrFail();
    }
}

src/app/Http/Controllers/Admin/StatusController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StatusRequest;
use App\Models\Status;
use Illuminate\Http\Request;
use Log;

class StatusController extends Controller
{
    public function index()
    {
        return view('admin/status/index', [
            'statuses' => Status::all(),
        ]);
    }

    public function show($id)
    {
        return view('admin/status/detail', [
            'status' => Status::find($id),
        ]);
    }

    public function create()
    {
        return view('admin/status/create');
    }

    public function store(StatusRequest $request)
    {
        $status = new Status;
        $status->fill($request->validated());
        $status->save();

        Log::debug('Status [id: '.$status->id.'] successfully stored');

        return redirect()->route('admin.status.show', $status->id)
                         ->with('success', 'Status stored');
    }

    public function edit($id)
    {
        return view('admin/status/update', [
            'status' => Status::find($id),
        ]);
    }

    public function update($id, StatusRequest $request)
    {
        $status = Status::find($id);
        $status->update($request->validated());

        Log::debug('Status [id: '.$status->id.'] successfully updated');

        return redirect()->route('admin.status.show', $status->id)
                         ->with('success', 'Status updated');
    }

    public function destroy($id)
    {
        Status::find($id)->delete();

        Log::debug('Status [id: '.$id.'] successfully destroyed');

        return redirect()->route('admin.status.index')
                         ->with('success', 'Status destroyed');
    }
}

src/resources/views/admin/status/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="card-header">
        <h1> ПА - [Statuses] </h1>
    </div>

    <div class="card-body">

        <form action="{{ route('admin.status.store') }}" method="post">

            @csrf

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Name <span class="text-danger">*</span> </span>
                </div>
                <input type="text" name="name" class="form-control">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Slug <span class="text-danger">*</span> </span>
                </div>
                <input type="text" name="slug" class="form-control">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Color_BG </span>
                </div>
                <input type="text" name="color_bg" class="form-control">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Color_FG </span>
                </div>
                <input type="text" name="color_fg" class="form-control">
            </div>

            <div class="btn-group mt-1" role="group" aria-label="Basic example">
                <a class="btn btn-primary" href="{{ route('admin.status.index') }}"> Back </a>
                <button class="btn btn-success" type="submit"> Store </button>
            </div>

        </form>

    </div>

@endsection

src/resources/views/admin/status/detail.blade.php
@extends('layouts.app')

@section('content')
    <div class="card-header">
        <h1> Dashboard - [Statuses] {{ $status->name }} </h1>
    </div>

    <div class="card-body">

        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $status->id ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> id </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $status->name ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> name </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $status->slug ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> slug </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $status->color_bg ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> color_bg </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $status->color_fg ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> color_fg </span>
            </li>
        </ul>

        <div class="btn-group mt-1" role="group" aria-label="Basic example">
            <a class="btn btn-primary" href="{{ route('admin.status.index') }}"> Back </a>
            <a class="btn btn-success" href="{{ route('admin.status.edit', $status->id) }}"> Edit </a>
            <a class="btn btn-danger" href="{{ route('admin.status.destroy', $status->id) }}"> Destroy </a>
        </div>

    </div>

@endsection

src/resources/views/admin/status/index.blade.php
@extends('layouts.app')

@section('content')

    @include('admin.includes.links')

    <div class="card">

        <div class="card-header black">
            <h1 class="h1 white-text text-uppercase"> Statuses table </h1>
        </div>

        <div class="card-body">
            <table class="table table-striped table-bordered table-hover table-sm table-responsive text-nowrap text-center">
                <thead>
                    <tr>
                        <th scope="col"> ID </th>
                        <th scope="col"> name </th>
                        <th scope="col"> slug </th>
                        <th scope="col"> color bg </th>
                        <th scope="col"> color fg </th>
                        <th scope="col"> tools </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($statuses as $status)
                        <tr>
                            <th scope="row"> {{ $status->id }} </th>
                            <td> {{ $status->name }} </td>
                            <td> {{ $status->slug }} </td>
                            <td> {{ $status->color_bg }} </td>
                            <td> {{ $status->color_fg }} </td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    <a type="button" class="btn btn-dark" href="{{ route('admin.status.show', $status->id) }}"> <i class="fas fa-info"></i> </a>
                                    <a type="button" class="btn btn-dark" href="{{ route('admin.status.edit', $status->id) }}"> <i class="fas fa-edit"></i> </a>
                                    <a type="button" class="btn btn-danger" href="{{ route('admin.status.destroy', $status->id) }}"> <i class="fas fa-trash"></i> </a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th scope="col"> ID </th>
                        <th scope="col"> name </th>
                        <th scope="col"> slug </th>
                        <th scope="col"> color bg </th>
                        <th scope="col"> color fg </th>
                        <th scope="col"> tools </th>
                    </tr>
                </tfoot>
            </table>
        </div>

        <div class="card-footer black">
            <div class="btn-group" role="group" aria-label="Basic example">
                <a class="btn btn-white black-text" href="{{ route('admin.status.create') }}"> Store <i class="fas fa-plus"></i> </a>
            </div>

        </div>

    </div>

    @include('admin.includes.tables')

@endsection

src/resources/views/admin/status/update.blade.php
@extends('layouts.app')

@section('content')

    <div class="card-header">
        <h1> Dashboard - [Statuses] {{ $status->name }} </h1>
    </div>

    <div class="card-body">

        <form action="{{ route('admin.status.update', $status->id) }}" method="post">

            @csrf

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Name </span>
                </div>
                <input type="text" name="name" class="form-control" value="{{ $status->name }}">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Slug </span>
                </div>
                <input type="text" name="slug" class="form-control" value="{{ $status->slug }}">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Color_BG </span>
                </div>
                <input type="text" name="color_bg" class="form-control" value="{{ $status->color_bg }}">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Color_FG </span>
                </div>
                <input type="text" name="color_fg" class="form-control" value="{{ $status->color_fg }}">
            </div>

            <div class="btn-group mt-1" role="group" aria-label="Basic example">
                <a class="btn btn-primary" href="{{ route('admin.status.show', $status->id) }}"> Back </a>
                <button class="btn btn-success" type="submit"> Update </button>
            </div>

        </form>

    </div>

@endsection