src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::group(['prefix' => '/', 'as' => 'site.', 'middleware' => 'locale'], function() {
    Route::get('/', 'Site\IndexController@index')->name('index');
    Route::get('/locale/{locale}', 'Site\LanguageController@setLocale')->name('locale');
    Route::group(['prefix' => '/product', 'as' => 'product.'], function() {
        Route::get('/all', 'Site\ProductController@index')->name('index');
        Route::get('/{slug}', 'Site\ProductController@show')->name('show');
    });
    Route::group(['prefix' => '/review', 'as' => 'review.'], function() {
        Route::post('/store', 'Site\ReviewController@store')->name('store');
    });
});

Route::group(['prefix' => '/admin', 'as' => 'admin.', 'middleware' => ['admin', 'locale']], function() {

    Route::get('/', 'Admin\AdminController@index')->name('index');

    Route::group(['prefix' => '/user', 'as' => 'user.'], function() {
        Route::get('/all', 'Admin\UserController@index')->name('index');
        Route::get('/create', 'Admin\UserController@create')->name('create');
        Route::post('/store', 'Admin\UserController@store')->name('store');
        Route::get('/{id}', 'Admin\UserController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\UserController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\UserController@update')->name('update');
        Route::get('/{id}/edit/password', 'Admin\UserController@editPassword')->name('edit.password');
        Route::post('/{id}/update/password', 'Admin\UserController@updatePassword')->name('update.password');
        Route::get('/{id}/destroy', 'Admin\UserController@destroy')->name('destroy');
    });

    Route::group(['prefix' => '/role', 'as' => 'role.'], function() {
        Route::get('/all', 'Admin\RoleController@index')->name('index');
        Route::get('/create', 'Admin\RoleController@create')->name('create');
        Route::post('/store', 'Admin\RoleController@store')->name('store');
        Route::get('/{id}', 'Admin\RoleController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\RoleController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\RoleController@update')->name('update');
        Route::get('/{id}/destroy', 'Admin\RoleController@destroy')->name('destroy');
    });

    Route::group(['prefix' => '/product', 'as' => 'product.'], function() {
        Route::get('/all', 'Admin\ProductController@index')->name('index');
        Route::get('/create', 'Admin\ProductController@create')->name('create');
        Route::post('/store', 'Admin\ProductController@store')->name('store');
        Route::get('/{id}', 'Admin\ProductController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\ProductController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\ProductController@update')->name('update');
        Route::get('/{id}/destroy', 'Admin\ProductController@destroy')->name('destroy');
    });

    Route::group(['prefix' => '/status', 'as' => 'status.'], function() {
        Route::get('/all', 'Admin\StatusController@index')->name('index');
        Route::get('/create', 'Admin\StatusController@create')->name('create');
        Route::post('/store', 'Admin\StatusController@store')->name('store');
        Route::get('/{id}', 'Admin\StatusController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\StatusController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\StatusController@update')->name('update');
        Route::get('/{id}/destroy', 'Admin\StatusController@destroy')->name('destroy');
    });
    Route::group(['prefix' => '/review', 'as' => 'review.'], function() {
        Route::get('/all', 'Admin\ReviewController@index')->name('index');
        Route::get('/create', 'Admin\ReviewController@create')->name('create');
        Route::post('/store', 'Admin\ReviewController@store')->name('store');
        Route::get('/{id}', 'Admin\ReviewController@show')->name('show');
        Route::get('/{id}/edit', 'Admin\ReviewController@edit')->name('edit');
        Route::post('/{id}/update', 'Admin\ReviewController@update')->name('update');
        Route::get('/{id}/destroy', 'Admin\ReviewController@destroy')->name('destroy');
    });

});

src/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function isAdmin()
    {
        return $this->role->name == 'admin';
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function reviews()
    {
        return $this->hasMany(Review::class);
    }
}

src/app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\Http\Requests\UserUpdateRequest;
use App\Http\Requests\UserUpdatePasswordRequest;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Log;

class UserController extends Controller
{

    public function index()
    {
        return view('admin/user/index', [
            'users' => User::all(),
        ]);
    }

    public function show($id)
    {
        return view('admin/user/detail', [
            'user' => User::find($id),
        ]);
    }

    public function create() {
        return view('admin/user/create');
    }

    public function store(UserRequest $request) {
        $user = new User;
        $user->fill($request->validated());
        $user->password = Hash::make($request->input('password'));
        $user->save();

        Log::debug('User [id: '.$user->id.'] successfully stored');

        return redirect()->route('admin.user.show', $user->id)
                         ->with('success', 'User stored');
    }

    public function edit($id) {
        return view('admin/user/update', [
            'user' => User::find($id),
        ]);
    }

    public function update($id, UserUpdateRequest $request)
    {
        $user = User::find($id);
        $user->update($request->validated());

        Log::debug('User [id: '.$user->id.'] successfully updated');

        return redirect()->route('admin.user.show', $user->id)
                         ->with('success', 'User updated');
    }

    public function editPassword($id)
    {
        return view('admin/user/update-password', [
            'user' => User::find($id),
        ]);
    }

    public function updatePassword($id, UserUpdatePasswordRequest $request)
    {
        $user = User::find($id);
        $user->password = Hash::make($request->input('password'));
        $user->update();

        Log::debug('User [id: '.$user->id.'] successfully updated');

        return redirect()->route('admin.user.show', $user->id)
                         ->with('success', 'User password updated');
    }

    public function destroy($id)
    {
        User::find($id)->delete();

        Log::debug('User [id: '.$id.'] successfully destroyed');

        return redirect()->route('admin.user.index')
                         ->with('success', 'User destroyed');
    }
}

src/resources/views/admin/user/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="card-header">
        <h1> ПА - [Users] </h1>
    </div>

    <div class="card-body">

        <form action="{{ route('admin.user.store') }}" method="post">

            @csrf

            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Name <span class="text-danger">*</span> </span>
                </div>
                <input type="text" name="name" class="form-control">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> E-mail <span class="text-danger">*</span> </span>
                </div>
                <input type="email" name="email" class="form-control">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Password <span class="text-danger">*</span> </span>
                </div>
                <input type="password" name="password" class="form-control">
            </div>

            <div class="btn-group mt-1" role="group" aria-label="Basic example">
                <a class="btn btn-primary" href="{{ route('admin.user.index') }}"> Back </a>
                <button class="btn btn-success" type="submit"> Store </button>
            </div>

        </form>

    </div>

@endsection

src/resources/views/admin/user/detail.blade.php
@extends('layouts.app')

@section('content')

    <div class="card-header">
        <h1> Dashboard - [Users] {{ $user->name }} </h1>
    </div>

    <div class="card-body">

        <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $user->id ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> id </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $user->name ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> name </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $user->email ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> email </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $user->email_verifiead_at ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> email_verifiead_at </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $user->password ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> password </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $user->remember_token ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> remember_token </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $user->role->name ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> role </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $user->created_at ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> created_at </span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                {{ $user->updated_at ?: 'Null' }}
                <span class="badge badge-primary badge-pill"> updated_at </span>
            </li>
        </ul>

        <div class="btn-group mt-1" role="group" aria-label="Basic example">
            <a class="btn btn-primary" href="{{ route('admin.user.index') }}"> Back </a>
            <a class="btn btn-success" href="{{ route('admin.user.edit', $user->id) }}"> Edit </a>
            <a class="btn btn-success" href="{{ route('admin.user.edit.password', $user->id) }}"> Change password </a>
            <a class="btn btn-danger" href="{{ route('admin.user.destroy', $user->id) }}"> Destroy </a>
        </div>

    </div>

@endsection

src/resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('content')

    @include('admin.includes.links')

    <div class="card">

        <div class="card-header black">
            <h1 class="h1 white-text text-uppercase"> Users table </h1>
        </div>

        <div class="card-body">
            <table class="table table-striped table-bordered table-hover table-sm table-responsive text-nowrap text-center">
                <thead>
                    <tr>
                        <th scope="col"> ID </th>
                        <th scope="col"> name </th>
                        <th scope="col"> email </th>
                        <th scope="col"> email verified at </th>
                        <th scope="col"> password </th>
                        <th scope="col"> role </th>
                        <th scope="col"> remember token </th>
                        <th scope="col"> created at </th>
                        <th scope="col"> updated at </th>
                        <th scope="col"> tools </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($users as $user)
                        <tr>
                            <th scope="row"> {{ $user->id }} </th>
                            <td> {{ $user->name }} </td>
                            <td> {{ $user->email }} </td>
                            <td> {{ $user->email_verified_at }} </td>
                            <td> {{ $user->password }} </td>
                            <td> @if ($user->role) {{ $user->role->name }} @endif </td>
                            <td> {{ $user->remember_token }} </td>
                            <td> {{ $user->created_at }} </td>
                            <td> {{ $user->updated_at }} </td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    <a type="button" class="btn btn-dark" href="{{ route('admin.user.show', $user->id) }}"> <i class="fas fa-info"></i> </a>
                                    <a type="button" class="btn btn-dark" href="{{ route('admin.user.edit', $user->id) }}"> <i class="fas fa-edit"></i> </a>
                                    <a type="button" class="btn btn-danger" href="{{ route('admin.user.destroy', $user->id) }}"> <i class="fas fa-trash"></i> </a>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th scope="col"> ID </th>
                        <th scope="col"> name </th>
                        <th scope="col"> email </th>
                        <th scope="col"> email verified at </th>
                        <th scope="col"> password </th>
                        <th scope="col"> role </th>
                        <th scope="col"> remember token </th>
                        <th scope="col"> created at </th>
                        <th scope="col"> updated at </th>
                        <th scope="col"> tools </th>
                    </tr>
                </tfoot>
            </table>
        </div>

        <div class="card-footer black">
            <div class="btn-group" role="group" aria-label="Basic example">
                <a class="btn btn-white black-text" href="{{ route('admin.user.create') }}"> Store <i class="fas fa-plus"></i> </a>
            </div>

        </div>

    </div>

    @include('admin.includes.tables')

@endsection

src/resources/views/admin/user/update-password.blade.php
@extends('layouts.app')

@section('content')

    <div class="card-header">
        <h1> Dashboard - [Users] {{$user->name}} </h1>
    </div>

    <div class="card-body">

        <form action="{{ route('admin.user.update.password', $user->id) }}" method="post">
            @csrf
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Password </span>
                </div>
                <input type="password" name="password" class="form-control">
            </div>
            <div class="btn-group mt-1" role="group" aria-label="Basic example">
                <a class="btn btn-primary" href="{{ route('admin.user.show', $user->id) }}"> Back </a>
                <button class="btn btn-success" type="submit"> Update </button>
            </div>
        </form>

    </div>

@endsection

src/resources/views/admin/user/update.blade.php
@extends('layouts.app')

@section('content')

    <div class="card-header">
        <h1> Dashboard - [Users] {{ $user->name }} </h1>
    </div>

    <div class="card-body">

        <form action="{{ route('admin.user.update', $user->id) }}" method="post">
            @csrf
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> Name </span>
                </div>
                <input type="text" name="name" class="form-control" value="{{ $user->name }}">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"> E-mail </span>
                </div>
                <input type="email" name="email" class="form-control" value="{{ $user->email }}">
            </div>
            <div class="btn-group mt-1" role="group" aria-label="Basic example">
                <a class="btn btn-primary" href="{{ route('admin.user.show', $user->id) }}"> Back </a>
                <button class="btn btn-success" type="submit"> Update </button>
            </div>
        </form>

    </div>

@endsection